name: DaCapo Tests

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup environments
        run: |
          if [ -d "/usr/lib/jvm" ]; then
            echo "start before ci-checkout /usr/lib/jvm exists:"
            ls -l /usr/lib/jvm/
          else
            echo "start before ci-checkout /usr/lib/jvm does not exist"
          fi

          ./.github/scripts/ci-checkout.sh

          if [ -d "/usr/lib/jvm" ]; then
            echo "after ci-checkout /usr/lib/jvm exists:"
            ls -l /usr/lib/jvm/
          else
            echo "after ci-checkout /usr/lib/jvm does not exist"
          fi

          ./.github/scripts/ci-setup.sh

          if [ -d "/usr/lib/jvm" ]; then
            echo "after ci-setup /usr/lib/jvm exists:"
            ls -l /usr/lib/jvm/
          else
            echo "after ci-setup /usr/lib/jvm does not exist"
          fi

      # Run the tests
      - name: DaCapo Tests
        run: |
          ./.github/scripts/ci-build.sh
          ./.github/scripts/ci-test-only-normal.sh
      - name: DaCapo Tests with valid object bit (VO bit)
        run: ./.github/scripts/ci-test-vo-bit.sh
      - name: DaCapo Tests with malloc Mark-Sweep
        run: ./.github/scripts/ci-test-malloc-mark-sweep.sh

      # Style check
      - name: Style checks
        run: ./.github/scripts/ci-style.sh